# Generated by Django 5.1.6 on 2025-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizdapanel',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
