# Generated by Django 5.1.6 on 2025-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_hakkimizdapanel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizdapanel',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
