# Generated by Django 5.1.5 on 2025-02-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meslek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meslek_adi', models.CharField(max_length=100)),
                ('en_dusuk_maas', models.IntegerField()),
                ('ortalama_maas', models.IntegerField()),
                ('en_yuksek_maas', models.IntegerField()),
                ('ankete_katilan_sayisi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yetenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetenek_adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeslekBolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzde', models.IntegerField()),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.bolum')),
                ('meslek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.meslek')),
            ],
        ),
        migrations.AddField(
            model_name='meslek',
            name='bolumler',
            field=models.ManyToManyField(through='MeslekSorgulama.MeslekBolum', to='MeslekSorgulama.bolum'),
        ),
        migrations.CreateModel(
            name='MeslekSektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzde', models.IntegerField()),
                ('meslek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.meslek')),
                ('sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.sektor')),
            ],
        ),
        migrations.AddField(
            model_name='meslek',
            name='sektorler',
            field=models.ManyToManyField(through='MeslekSorgulama.MeslekSektor', to='MeslekSorgulama.sektor'),
        ),
        migrations.CreateModel(
            name='MeslekYetenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meslek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.meslek')),
                ('yetenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.yetenek')),
            ],
        ),
        migrations.AddField(
            model_name='meslek',
            name='yetenekler',
            field=models.ManyToManyField(through='MeslekSorgulama.MeslekYetenek', to='MeslekSorgulama.yetenek'),
        ),
    ]
