# Generated by Django 5.1.5 on 2025-02-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Yetenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetenek', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meslek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meslek_adi', models.CharField(max_length=100)),
                ('en_dusuk_maas', models.IntegerField()),
                ('ortalama_maas', models.IntegerField()),
                ('en_yuksek_maas', models.IntegerField()),
                ('ankete_katilan_sayisi', models.IntegerField()),
                ('sektor_yuzde', models.IntegerField()),
                ('bolum_yuzde', models.IntegerField()),
                ('Bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.bolum')),
                ('Sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.sektor')),
                ('Yetenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeslekSorgulama.yetenek')),
            ],
        ),
    ]
