# Generated by Django 5.1.5 on 2025-02-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeslekSorgulama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslek',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
