# Generated by Django 5.1.6 on 2025-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeslekSorgulama', '0002_meslek_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meslek',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
