# Generated by Django 5.1.6 on 2025-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
                ('factor', models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')])),
                ('soruEN', models.TextField()),
                ('soruTR', models.TextField()),
            ],
        ),
    ]
