# Generated by Django 5.1.6 on 2025-03-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KisilikTesti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorular',
            name='soruTR',
            field=models.TextField(blank=True, null=True),
        ),
    ]
