# Generated by Django 5.1.6 on 2025-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KisilikTesti', '0002_alter_sorular_sorutr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kisilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
                ('alt_sınır', models.IntegerField()),
                ('ust_sınır', models.IntegerField()),
                ('dusuk_aciklama', models.TextField()),
                ('ortalama_aciklama', models.TextField()),
                ('yuksek_aciklama', models.TextField()),
            ],
        ),
    ]
