# Generated by Django 5.1.6 on 2025-03-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KisilikTesti', '0004_remove_kisilik_id_alter_kisilik_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorular',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KisilikTesti.kisilik'),
        ),
    ]
