# Generated by Django 5.1.6 on 2025-03-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KisilikTesti', '0005_alter_sorular_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kisilik',
            old_name='alt_sınır',
            new_name='alt_sinir',
        ),
        migrations.RenameField(
            model_name='kisilik',
            old_name='ust_sınır',
            new_name='ust_sinir',
        ),
    ]
